spring.application.name=Galeria

# ==============================================================
# 1. CONFIGURACI�N DEL SERVIDOR
# ==============================================================
# Puerto donde correr� la API de Spring Boot
server.port=8080

# ==============================================================
# 2. CONEXI�N A LA BASE DE DATOS POSTGRESQL (DOCKER)
# ==============================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-spring-boot:5432/museo_db}
spring.datasource.username=Miguel
# contrase�a del  contenedor de Docker
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# 3. CONFIGURACI�N DE JPA / HIBERNATE
# ==============================================================
# 'none' le dice a Spring Boot que NO cree las tablas
# autom�ticamente, sino con un  script SQL propio.
spring.jpa.hibernate.ddl-auto=update

# Esto ayuda a Hibernate a entender d�nde termina cada comando SQL
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.sql_exception_converter=org.hibernate.exception.internal.StandardSQLExceptionConverter


# Asegura que el import sql se ejecute DESPU�S de crear las tablas
spring.sql.init.mode=always

# Muestra en la consola de Spring las consultas SQL que se ejecutan
spring.jpa.show-sql=true

# Le da un formato bonito y legible al SQL en la consola
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Para evitar problemas con la carga de objetos pesados (Lazy Loading)
spring.jackson.serialization.fail-on-empty-beans=false

# ==============================================================
# 4. CONEXIÓN A MONGODB (Catálogo Dinámico)
# ==============================================================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongodb-galeria:27017/galeria_catalog}
spring.data.mongodb.database=galeria_catalog